project_name: tenet
dist: bin/
builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/tenet-controller
    goos:
      - linux
    goarch:
      - amd64
      - arm64
dockers:
  - image_templates:
    - "quay.io/cybozu/{{.ProjectName}}:{{ .Version }}-amd64"
    - "ghcr.io/cybozu-go/{{.ProjectName}}:{{ .Version }}-amd64"
    use: buildx
    dockerfile: Dockerfile
    extra_files:
      - LICENSE
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - image_templates:
    - "quay.io/cybozu/{{.ProjectName}}:{{ .Version }}-arm64"
    - "ghcr.io/cybozu-go/{{.ProjectName}}:{{ .Version }}-arm64"
    use: buildx
    goarch: arm64
    dockerfile: Dockerfile
    extra_files:
      - LICENSE
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
docker_manifests:
  - name_template: "quay.io/cybozu/{{.ProjectName}}:{{ .Version }}"
    image_templates:
      - "quay.io/cybozu/{{.ProjectName}}:{{ .Version }}-amd64"
      - "quay.io/cybozu/{{.ProjectName}}:{{ .Version }}-arm64"
  - name_template: "quay.io/cybozu/{{.ProjectName}}:{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "quay.io/cybozu/{{.ProjectName}}:{{ .Version }}-amd64"
      - "quay.io/cybozu/{{.ProjectName}}:{{ .Version }}-arm64"
  - name_template: "ghcr.io/cybozu-go/{{.ProjectName}}:{{ .Version }}"
    image_templates:
      - "ghcr.io/cybozu-go/{{.ProjectName}}:{{ .Version }}-amd64"
      - "ghcr.io/cybozu-go/{{.ProjectName}}:{{ .Version }}-arm64"
  - name_template: "ghcr.io/cybozu-go/{{.ProjectName}}:{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "ghcr.io/cybozu-go/{{.ProjectName}}:{{ .Version }}-amd64"
      - "ghcr.io/cybozu-go/{{.ProjectName}}:{{ .Version }}-arm64"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
