
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-cilium-io-v2-ciliumnetworkpolicy
  failurePolicy: Fail
  name: vciliumnetworkpolicy.kb.io
  rules:
  - apiGroups:
    - cilium.io
    apiVersions:
    - v2
    operations:
    - CREATE
    - UPDATE
    resources:
    - ciliumnetworkpolicies
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-tenet-cybozu-io-v1beta1-networkpolicyadmissionrule
  failurePolicy: Fail
  name: vnetworkpolicyadmissionrule.kb.io
  rules:
  - apiGroups:
    - tenet.cybozu.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - networkpolicyadmissionrules
  sideEffects: None
