resources:
  - ../../../rbac
  - ../../../webhook

namespace: '{{ .Release.Namespace }}'

namePrefix: '{{ template "tenet.fullname" . }}-'

commonLabels:
  app.kubernetes.io/name: '{{ include "tenet.name" . }}'

patchesStrategicMerge:
  - webhookcainjection_patch.yaml

transformers:
  - label-transformer.yaml
