# permissions for end users to edit networkpolicyadmissionrules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: networkpolicyadmissionrule-editor-role
rules:
- apiGroups:
  - tenet.cybozu.io
  resources:
  - networkpolicyadmissionrules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tenet.cybozu.io
  resources:
  - networkpolicyadmissionrules/status
  verbs:
  - get
