apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    cert-manager.io/inject-ca-from: '{{ .Release.Namespace }}/{{ template "tenet.fullname" . }}-serving-cert'
  name: networkpolicyadmissionrules.tenet.cybozu.io
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          namespace: '{{ .Release.Namespace }}'
          name: '{{ template "tenet.fullname" . }}-webhook-service'
          path: /convert
      conversionReviewVersions:
        - v1
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    cert-manager.io/inject-ca-from: '{{ .Release.Namespace }}/{{ template "tenet.fullname" . }}-serving-cert'
  name: networkpolicytemplates.tenet.cybozu.io
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          namespace: '{{ .Release.Namespace }}'
          name: '{{ template "tenet.fullname" . }}-webhook-service'
          path: /convert
      conversionReviewVersions:
        - v1
