apiVersion: builtin
kind: LabelTransformer
metadata:
  name: helm-metadata-labels
labels:
  helm.sh/chart: '{{ include "tenet.chart" . }}'
  app.kubernetes.io/name: '{{ include "tenet.name" . }}'
  app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
  app.kubernetes.io/managed-by: '{{ .Release.Service }}'
fieldSpecs:
  - path: metadata/labels
    create: true
