image:
  # image.repository -- Tenet image repository to use.
  repository: ghcr.io/cybozu-go/tenet

  # image.tag -- Tenet image tag to use.
  # @default -- `{{ .Chart.AppVersion }}`
  tag:  # 0.1.0

  # image.pullPolicy -- Tenet image pullPolicy.
  pullPolicy:  # Always

controller:
  # controller.replicas -- Specify the number of replicas of the controller Pod.
  replicas: 2

  # controller.resources -- Specify resources.
  resources:
    requests:
      cpu: 100m
      memory: 64Mi

  # controller.terminationGracePeriodSeconds -- Specify terminationGracePeriodSeconds.
  terminationGracePeriodSeconds: 10

  # controller.extraArgs -- Optional additional arguments.
  extraArgs:
    - --leader-elect
