name: main
on:
  pull_request:
  push:
    branches:
      - 'main'
    tags-ignore:
      - '*'
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Test
        run: make build
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Lint
        run: make lint
  check-goreleaser-config:
    name: Check goreleaser.yml
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: check -f .goreleaser.yml
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Test
        run: make test
  e2e:
    name: End-to-End Tests
    strategy:
      matrix:
        k8s-version: ["1.20.7", "1.21.2", "1.22.4"]
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - run: make start KUBERNETES_VERSION=${{ matrix.k8s-version }}
      working-directory: e2e
    - run: make test
      working-directory: e2e
    - run: make logs
      working-directory: e2e
      if: always()
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: logs-${{ matrix.k8s-version }}.tar.gz
        path: e2e/logs.tar.gz
  dry-run:
    name: Dry-run release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Setup tag for goreleaser
        run: |
          echo "GORELEASER_CURRENT_TAG=$(git describe --tags --abbrev=0 --match "v*" || echo v0.0.0)" >> $GITHUB_ENV
      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: --snapshot --skip-publish --rm-dist
      - name: Test built containers
        run: make container-structure-test
