name: Lint and Test Charts
on:
  pull_request:
    paths:
      - "charts/**"
      - '!**.md'
jobs:
  lint-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
      - name: Set up chart-testing
        uses: helm/chart-testing-action@e6669bcd63d7cb57cb4380c33043eebe5d111992 # 2.6.1
      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config ct.yaml)
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
      - name: Run chart-testing (lint)
        run: ct lint --config ct.yaml
      - name: Create kind cluster
        uses: helm/kind-action@0025e74a8c7512023d06dc019c617aa3cf561fde # 1.10.0
        if: steps.list-changed.outputs.changed == 'true'
        with:
          node_image: kindest/node:v1.27.3
          version: v0.24.0
      - name: Apply cert-manager
        run: |
          kubectl apply -f https://github.com/jetstack/cert-manager/releases/latest/download/cert-manager.yaml
          kubectl -n cert-manager wait --for=condition=available --timeout=180s --all deployments
      - name: Run chart-testing (install)
        run: ct install --config ct.yaml
